/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';

import '../../../../themes/stack_colors.dart';
import '../../../../utilities/constants.dart';
import '../../../../utilities/text_styles.dart';
import '../../../../widgets/flag_secure_scope.dart';
import 'mnemonic_table_item.dart';

class MnemonicTable extends StatelessWidget {
  const MnemonicTable({
    super.key,
    required this.words,
    required this.isDesktop,
    this.itemBorderColor,
  });

  final List<String> words;
  final bool isDesktop;
  final Color? itemBorderColor;

  @override
  Widget build(BuildContext context) {
    debugPrint("BUILD: $runtimeType");
    // A BEAM wallet imported from its wallet.db has no phrase: say so
    // rather than show an empty grid.
    if (words.isEmpty) return NoRecoveryPhraseNotice(isDesktop: isDesktop);
    final wordsPerRow = isDesktop ? 4 : 3;

    final int rows = words.length ~/ wordsPerRow;

    final int remainder = words.length % wordsPerRow;

    int index = 0;

    // Recovery words: no screenshots, recordings or recents thumbnail.
    return FlagSecureScope(child: Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        for (int i = 1; i <= rows; i++)
          Padding(
            padding: EdgeInsets.symmetric(vertical: isDesktop ? 8 : 5),
            child: Row(
              children: [
                for (int j = 1; j <= wordsPerRow; j++) ...[
                  if (j > 1)
                    SizedBox(
                      width: isDesktop ? 10 : 6,
                    ),
                  Expanded(
                    child: MnemonicTableItem(
                      number: ++index,
                      word: words[index - 1],
                      isDesktop: isDesktop,
                      borderColor: itemBorderColor,
                    ),
                  ),
                ],
              ],
            ),
          ),
        if (index != words.length)
          Padding(
            padding: EdgeInsets.symmetric(vertical: isDesktop ? 8 : 5),
            child: Row(
              children: [
                for (int i = index; i < words.length; i++) ...[
                  if (i > index)
                    SizedBox(
                      width: isDesktop ? 10 : 6,
                    ),
                  Expanded(
                    child: MnemonicTableItem(
                      number: i + 1,
                      word: words[i],
                      isDesktop: isDesktop,
                      borderColor: itemBorderColor,
                    ),
                  ),
                ],
                for (int i = remainder; i < wordsPerRow; i++) ...[
                  const SizedBox(
                    width: 6,
                  ),
                  Expanded(
                    child: Container(),
                  ),
                ],
              ],
            ),
          ),
      ],
    ));
  }
}

/// Shown wherever a recovery phrase would be, for a wallet that has none (a
/// BEAM wallet imported from its wallet.db file).
class NoRecoveryPhraseNotice extends StatelessWidget {
  const NoRecoveryPhraseNotice({super.key, required this.isDesktop});

  final bool isDesktop;

  static const text =
      'This wallet was imported from its wallet.db file and has no recovery '
      'phrase in BEAM Campfire. Its original file and password are its '
      'backup: keep them safe.';

  @override
  Widget build(BuildContext context) => Container(
    key: const ValueKey('no-recovery-phrase'),
    padding: EdgeInsets.all(isDesktop ? 20 : 16),
    decoration: BoxDecoration(
      color: Theme.of(context).extension<StackColors>()!.warningBackground,
      borderRadius: BorderRadius.circular(Constants.size.circularBorderRadius),
    ),
    child: Text(
      text,
      style: STextStyles.label(context).copyWith(
        color: Theme.of(context).extension<StackColors>()!.warningForeground,
      ),
    ),
  );
}
