/*
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

import '../app_config.dart';
import '../models/notification_model.dart';
import '../utilities/beam_app_identity.dart';
import '../utilities/logger.dart';
import '../utilities/prefs.dart';
import '../wallets/beam/wallet/beam_payment_notice.dart';
import 'notifications_service.dart';

abstract final class NotificationApi {
  static Completer<void>? _initCalledCompleter;
  static final _notifications = FlutterLocalNotificationsPlugin();
  // static final onNotifications = BehaviorSubject<String?>();

  static Future<NotificationDetails> _notificationDetails() async {
    return const NotificationDetails(
      android: AndroidNotificationDetails(
        'channel id',
        'channel name',
        channelDescription: 'channel description',
        // importance: Importance.max,
        priority: Priority.high,
        ticker: 'ticker',
      ),
      iOS: DarwinNotificationDetails(),
      macOS: DarwinNotificationDetails(),
    );
  }

  static Future<void> init({bool initScheduled = false}) async {
    if (_initCalledCompleter == null) {
      _initCalledCompleter = Completer<void>();
    } else {
      if (_initCalledCompleter!.isCompleted) {
        return;
      } else {
        return await _initCalledCompleter!.future;
      }
    }

    const android = AndroidInitializationSettings('app_icon_alpha');
    // Campfire for BEAM asks for permission the first time it has something
    // to show (a payment arrived, see [_askPermissionOnce]), not at launch,
    // before the user has done anything.
    final darwin = BeamAppIdentity.isActive
        ? const DarwinInitializationSettings(
            requestAlertPermission: false,
            requestBadgePermission: false,
            requestSoundPermission: false,
          )
        : const DarwinInitializationSettings();
    final iOS = darwin;
    const linux = LinuxInitializationSettings(
      defaultActionName: "temporary_stack_wallet",
    );
    final macOS = darwin;
    final (windowsAppUserModelId, windowsGuid) = switch (AppConfig.appName) {
      // Same name as Campfire, but not the same Windows notification identity.
      "Campfire" when BeamAppIdentity.isActive => (
        "vsnation.CampfireBEAM",
        "1b91c91f-eaf9-48ea-9691-474b7e974060",
      ),
      "Campfire" => (
        "CypherStack.Campfire",
        "fe1bb964-a80c-45cd-a5d6-c95b2d8b1142",
      ),
      "Stack Duo" => (
        "CypherStack.StackDuo",
        "7b01c69c-c282-493e-98a1-6a5cd3153049",
      ),
      _ => ("CypherStack.StackWallet", "986f4b88-0a22-42c2-a005-e5e150c8653f"),
    };
    final windows = WindowsInitializationSettings(
      appName: AppConfig.appName,
      appUserModelId: windowsAppUserModelId,
      guid: windowsGuid,
    );
    final settings = InitializationSettings(
      android: android,
      iOS: iOS,
      linux: linux,
      macOS: macOS,
      windows: windows,
    );
    await _notifications.initialize(
      settings: settings,
      // onDidReceiveNotificationResponse: (payload) async {
      //   onNotifications.add(payload.payload);
      // },
      // onDidReceiveBackgroundNotificationResponse: (payload) async {
      //   onNotifications.add(payload.payload);
      // },
    );
    _initCalledCompleter!.complete();
  }

  static Future<void> clearNotifications() async {
    await init();
    await _notifications.cancelAll();
  }

  static Future<void> clearNotification(int id) async {
    await init();
    await _notifications.cancel(id: id);
  }

  //===================================
  static late Prefs prefs;
  static late NotificationsService notificationsService;

  static Future<void>? _asking;

  /// BEAM build: completes when the system's permission question may
  /// appear. It waits while a send, swap, claim or dApp approval is open
  /// ([beamNoMoneyFlowOpen]), so the question never lands on top of one.
  /// Only the system banner waits for it: the entry in Campfire's own list
  /// never does. Tests replace it.
  static Future<void> Function() permissionDialogMayShow =
      BeamAppIdentity.isActive ? beamNoMoneyFlowOpen : _now;

  static Future<void> _now() async {}

  /// Back to a fresh start (tests: the plugin, the question and the wait).
  @visibleForTesting
  static void debugReset() {
    _initCalledCompleter = null;
    _asking = null;
    permissionDialogMayShow = BeamAppIdentity.isActive
        ? beamNoMoneyFlowOpen
        : _now;
  }

  /// Whether asking would put a question on screen: false where nothing is
  /// asked (Linux, Windows) and where notifications are already allowed.
  static Future<bool> _questionWouldShow() async {
    final mac = _notifications.resolvePlatformSpecificImplementation<
      MacOSFlutterLocalNotificationsPlugin
    >();
    if (mac != null) {
      return !((await mac.checkPermissions())?.isEnabled ?? false);
    }
    final ios = _notifications.resolvePlatformSpecificImplementation<
      IOSFlutterLocalNotificationsPlugin
    >();
    if (ios != null) {
      return !((await ios.checkPermissions())?.isEnabled ?? false);
    }
    final android = _notifications.resolvePlatformSpecificImplementation<
      AndroidFlutterLocalNotificationsPlugin
    >();
    if (android != null) {
      return !(await android.areNotificationsEnabled() ?? false);
    }
    return false;
  }

  /// Asks once per run, at the first notification Campfire actually has to
  /// show (in the BEAM build: the first payment that arrives), never at
  /// launch; others asked at [init]. Not while a money flow is open
  /// ([permissionDialogMayShow]), and not at all when notifications are
  /// already allowed. Never throws: a refusal just means no banner; the
  /// notification still lands in Campfire's own list.
  static Future<void> _askPermissionOnce() => _asking ??= () async {
    try {
      if (!await _questionWouldShow()) return;
      await permissionDialogMayShow();
      await _notifications
          .resolvePlatformSpecificImplementation<
            MacOSFlutterLocalNotificationsPlugin
          >()
          ?.requestPermissions(alert: true, badge: true, sound: true);
      await _notifications
          .resolvePlatformSpecificImplementation<
            IOSFlutterLocalNotificationsPlugin
          >()
          ?.requestPermissions(alert: true, badge: true, sound: true);
      await _notifications
          .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin
          >()
          ?.requestNotificationsPermission();
    } catch (e, s) {
      Logging.instance.w(
        "Notification permission request failed",
        error: e,
        stackTrace: s,
      );
    }
  }();

  /// The system banner for an entry already in Campfire's list. Never
  /// throws: no permission or an unsigned build only means no banner.
  static Future<void> _showOsBanner({
    required int id,
    required String title,
    required String body,
    String? payload,
  }) async {
    try {
      await init();
      await _askPermissionOnce();
      await _notifications.show(
        id: id,
        title: title,
        body: body,
        notificationDetails: await _notificationDetails(),
        payload: payload,
      );
    } catch (e, s) {
      Logging.instance.w(
        "Notification banner not shown; it is in Campfire's list",
        error: e,
        stackTrace: s,
      );
    }
  }

  static Future<int> _showOsNotification({
    required String title,
    required String body,
    String? payload,
  }) async {
    await init();
    if (BeamAppIdentity.isActive) await _askPermissionOnce();
    final id = await prefs.incrementCurrentNotificationIndex();
    await _notifications.show(
      id: id,
      title: title,
      body: body,
      notificationDetails: await _notificationDetails(),
      payload: payload,
    );
    return id;
  }

  static Future<void> showNotification({
    required String title,
    required String body,
    required String walletId,
    required String iconAssetName,
    required DateTime date,
    required bool shouldWatchForUpdates,
    required String coinName,
    String? txid,
    int? confirmations,
    int? requiredConfirmations,
    String? changeNowId,
    String? payload,
  }) async {
    final int id;
    if (BeamAppIdentity.isActive) {
      // Campfire for BEAM: the entry in Campfire's own list never depends
      // on the system banner. An ad-hoc signed build, or a user who said no,
      // makes the banner fail, and the list entry used to be lost with it
      // (seen in the DMG test: a received payment, an empty list).
      id = await prefs.incrementCurrentNotificationIndex();
      unawaited(
        _showOsBanner(id: id, title: title, body: body, payload: payload),
      );
    } else {
      id = await _showOsNotification(
        title: title,
        body: body,
        payload: payload,
      );
    }

    String confirms = "";
    if (txid != null &&
        confirmations != null &&
        requiredConfirmations != null) {
      confirms = " ($confirmations/$requiredConfirmations)";
    }

    final NotificationModel model = NotificationModel(
      id: id,
      title: title + confirms,
      description: body,
      iconAssetName: iconAssetName,
      date: date,
      walletId: walletId,
      read: false,
      shouldWatchForUpdates: shouldWatchForUpdates,
      coinName: coinName,
      txid: txid,
      changeNowId: changeNowId,
    );

    await notificationsService.add(model, true);
  }

  static Future<void> showLocalOnly({
    required String title,
    required String body,
  }) async {
    try {
      await _showOsNotification(title: title, body: body);
    } catch (e, s) {
      Logging.instance.w(
        "NotificationApi.showLocalOnly failed",
        error: e,
        stackTrace: s,
      );
    }
  }
}
