/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../../app_config.dart';
import '../../../themes/stack_colors.dart';
import '../../../utilities/assets.dart';
import '../../../utilities/beam_app_identity.dart';
import '../../../utilities/constants.dart';
import '../../../utilities/text_styles.dart';
import '../../../utilities/util.dart';
import '../../../widgets/background.dart';
import '../../../widgets/beam/airdrop/beam_layout.dart';
import '../../../widgets/conditional_parent.dart';
import '../../../widgets/custom_buttons/app_bar_icon_button.dart';
import '../../../widgets/desktop/primary_button.dart';
import '../../../widgets/desktop/secondary_button.dart';
import '../../../widgets/dialogs/s_dialog.dart';
import '../../../widgets/rounded_white_container.dart';

class SupportView extends StatelessWidget {
  const SupportView({super.key});

  static const String routeName = "/support";

  @override
  Widget build(BuildContext context) {
    debugPrint("BUILD: $runtimeType");

    // Util.isDesktop in the app; BeamLayoutScope lets a golden test on a
    // desktop host show the phone page.
    final isDesktop = BeamLayoutScope.isDesktop(context);

    return ConditionalParent(
      condition: !isDesktop,
      builder: (child) {
        return Background(
          child: Scaffold(
            backgroundColor: Theme.of(context)
                .extension<StackColors>()!
                .background,
            appBar: AppBar(
              leading: AppBarBackButton(
                onPressed: () {
                  Navigator.of(context).pop();
                },
              ),
              title: Text("Support", style: STextStyles.navBarTitle(context)),
            ),
            body: SafeArea(
              // BEAM's channels make a longer list than a small phone shows.
              child: SingleChildScrollView(
                padding: const EdgeInsets.all(16),
                child: child,
              ),
            ),
          ),
        );
      },
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          RoundedWhiteContainer(
            child: Text(
              // BEAM's official channels, as listed on beam.mw (owner,
              // 2026-10-08). Bugs in this app go to its GitHub issues.
              "Questions about BEAM or your wallet: BEAM's support team and "
              "community are on these channels. Found a bug in this app? "
              "Tell us on GitHub.",
              style: STextStyles.smallMed12(context),
            ),
          ),
          isDesktop ? const SizedBox(height: 24) : const SizedBox(height: 12),
          AboutItem(
            linkUrl: "https://t.me/BeamSupport",
            label: "Support chat",
            buttonText: "@BeamSupport",
            channel: "the support chat",
            iconAsset: Assets.socials.telegram,
            isDesktop: isDesktop,
          ),
          const SizedBox(height: 8),
          AboutItem(
            linkUrl: "mailto:support@beam.mw",
            label: "Email",
            buttonText: "support@beam.mw",
            iconAsset: Assets.svg.envelope,
            isDesktop: isDesktop,
          ),
          const SizedBox(height: 8),
          AboutItem(
            linkUrl: "https://github.com/vsnation/campfire-beam/issues",
            label: "A bug in this app",
            buttonText: "GitHub Issues",
            channel: "GitHub Issues",
            iconAsset: Assets.svg.circleQuestion,
            isDesktop: isDesktop,
          ),
          const SizedBox(height: 8),
          AboutItem(
            linkUrl: "https://t.me/BeamPrivacy",
            label: "Telegram",
            buttonText: "@BeamPrivacy",
            iconAsset: Assets.socials.telegram,
            isDesktop: isDesktop,
          ),
          const SizedBox(height: 8),
          AboutItem(
            linkUrl: "https://discord.gg/BHZvAhg",
            label: "Discord",
            buttonText: "BEAM",
            iconAsset: Assets.socials.discord,
            isDesktop: isDesktop,
          ),
          const SizedBox(height: 8),
          AboutItem(
            linkUrl: "https://www.reddit.com/r/beamprivacy/",
            label: "Reddit",
            buttonText: "r/beamprivacy",
            iconAsset: Assets.socials.reddit,
            isDesktop: isDesktop,
          ),
          const SizedBox(height: 8),
          AboutItem(
            linkUrl: "https://x.com/beamprivacy",
            label: "X",
            buttonText: "@beamprivacy",
            iconAsset: Assets.socials.twitter,
            isDesktop: isDesktop,
          ),
          const SizedBox(height: 8),
          AboutItem(
            linkUrl: "https://forum.beam.mw",
            label: "Forum",
            buttonText: "forum.beam.mw",
            channel: "the forum",
            iconAsset: Assets.svg.questionMessage,
            isDesktop: isDesktop,
          ),
        ],
      ),
    );
  }
}

class AboutItem extends StatelessWidget {
  const AboutItem({
    super.key,
    required this.linkUrl,
    required this.label,
    required this.buttonText,
    required this.iconAsset,
    required this.isDesktop,
    this.channel,
  });

  final String linkUrl;
  final String label;
  final String buttonText;
  final String iconAsset;
  final bool isDesktop;

  /// What the scam warning calls the channel; [label] by default.
  final String? channel;

  @override
  Widget build(BuildContext context) {
    final double iconSize = isDesktop ? 20 : 28;

    return RoundedWhiteContainer(
      padding: const EdgeInsets.all(0),
      child: RawMaterialButton(
        // splashColor: Theme.of(context).extension<StackColors>()!.highlight,
        materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(
            Constants.size.circularBorderRadius,
          ),
        ),
        onPressed: () async {
          if (label == "Email") {
            await launchUrl(
              Uri.parse(linkUrl),
              mode: LaunchMode.externalApplication,
            );
          } else {
            await showDialog<void>(
              context: context,
              builder: (_) => ScamWarningDialog(
                channel: channel ?? label,
                onUnderstandPressed: () => launchUrl(
                  Uri.parse(linkUrl),
                  mode: LaunchMode.externalApplication,
                ),
              ),
            );
          }
        },
        child: Padding(
          padding: isDesktop
              ? const EdgeInsets.symmetric(horizontal: 20, vertical: 15)
              : const EdgeInsets.symmetric(horizontal: 12, vertical: 20),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Row(
                children: [
                  ConditionalParent(
                    condition: isDesktop,
                    builder: (child) => Container(
                      width: 40,
                      height: 40,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(10000),
                        color: Theme.of(context)
                            .extension<StackColors>()!
                            .buttonBackSecondary,
                      ),
                      child: Center(child: child),
                    ),
                    child: SvgPicture.asset(
                      iconAsset,
                      width: iconSize,
                      height: iconSize,
                      color: Theme.of(context)
                          .extension<StackColors>()!
                          .topNavIconPrimary,
                    ),
                  ),
                  const SizedBox(width: 12),
                  Text(
                    label,
                    style: STextStyles.titleBold12(context),
                    textAlign: TextAlign.left,
                  ),
                ],
              ),
              if (isDesktop)
                Text(
                  buttonText,
                  style: STextStyles.desktopTextExtraExtraSmall(context),
                ),
              // BlueTextButton(
              //   text: buttonText,
              //   onTap: () {
              //     launchUrl(
              //       Uri.parse(linkUrl),
              //       mode: LaunchMode.externalApplication,
              //     );
              //   },
              // ),
            ],
          ),
        ),
      ),
    );
  }
}

class ScamWarningDialog extends StatelessWidget {
  const ScamWarningDialog({
    super.key,
    required this.onUnderstandPressed,
    required this.channel,
  });

  final String channel;
  final VoidCallback onUnderstandPressed;

  @override
  Widget build(BuildContext context) {
    final body = Util.isDesktop
        ? STextStyles.w500_16(context)
        : STextStyles.w500_14(context);
    // BEAM's channels support BEAM, not this app alone.
    final who = BeamAppIdentity.isActive ? "BEAM's team" : AppConfig.appName;
    return SDialog(
      padding: EdgeInsets.all(Util.isDesktop ? 32 : 16),
      child: ConditionalParent(
        condition: Util.isDesktop,
        builder: (child) => ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 480),
          child: child,
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(
              "Real support is always public",
              style: Util.isDesktop
                  ? STextStyles.desktopH3(context)
                  : STextStyles.pageTitleH2(context),
            ),
            const SizedBox(height: 16),
            Text(
              "$who only ever helps in public. Anyone who writes to you "
              "privately first is not support.",
              style: body.copyWith(fontWeight: FontWeight.normal),
            ),
            const SizedBox(height: 16),
            const _Bullet(
              text:
                  "No one from support will ever ask for your recovery "
                  "phrase, password or private keys.",
            ),
            const SizedBox(height: 8),
            const _Bullet(
              text: "Anyone who asks you to send them coins is a scammer.",
            ),
            SizedBox(height: Util.isDesktop ? 32 : 24),
            LayoutBuilder(
              builder: (context, box) {
                final height = Util.isDesktop ? ButtonHeight.l : null;
                final open = PrimaryButton(
                  label: "Open $channel",
                  buttonHeight: height,
                  onPressed: () {
                    Navigator.of(context).pop();
                    onUnderstandPressed();
                  },
                );
                final cancel = SecondaryButton(
                  label: "Cancel",
                  buttonHeight: height,
                  onPressed: () => Navigator.of(context).pop(),
                );
                // Side by side when both fit; else the way in on top.
                if (box.maxWidth < 400) {
                  return Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [open, const SizedBox(height: 12), cancel],
                  );
                }
                return Row(
                  children: [
                    Expanded(child: cancel),
                    const SizedBox(width: 16),
                    Expanded(child: open),
                  ],
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}

class _Bullet extends StatelessWidget {
  const _Bullet({required this.text});

  final String text;

  @override
  Widget build(BuildContext context) {
    final style = Util.isDesktop
        ? STextStyles.w500_16(context)
        : STextStyles.w500_14(context);
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.only(left: 4, right: 10),
          child: Text("•", style: style),
        ),
        Expanded(child: Text(text, style: style)),
      ],
    );
  }
}
