/* 
 * This file is part of Stack Wallet.
 * 
 * Copyright (c) 2023 Cypher Stack
 * All Rights Reserved.
 * The code is distributed under GPLv3 license, see LICENSE file for details.
 * Generated by Cypher Stack on 2023-05-26
 *
 */

import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'prefs_provider.dart';
import '../../services/price_service.dart';

int _count = 0;

final priceAnd24hChangeNotifierProvider =
    ChangeNotifierProvider<PriceService>((ref) {
  if (kDebugMode) {
    _count++;
  }

  final currency =
      ref.watch(prefsChangeNotifierProvider.select((value) => value.currency));
  final service = PriceService(currency);
  // A currency change rebuilds this provider and disposes the old service
  // with its timer: without this, prices in the new currency were fetched
  // once (by the settings screen) and never refreshed again until restart.
  // The settings screen does the first fetch, so no request right away.
  if (PriceService.anyStarted) service.start(false);
  return service;
});
