// Regenerates src/vendor/fake-indexeddb/ from the npm package tarball.
//
//   npm pack fake-indexeddb@6.2.5
//   node tools/vendor_fake_indexeddb.mjs fake-indexeddb-6.2.5.tgz
//
// Why it is there: a dApp frame has an opaque origin, which has no
// IndexedDB, and two of BEAM's dApps (BEAM NFT Gallery and the name service)
// store through Dexie and stop without it. fake-indexeddb is a pure-JS,
// in-memory IndexedDB (Apache-2.0). It runs only inside dApp frames, never in
// the wallet's own page, and keeps nothing after the dApp is closed.
//
// The tarball must match the pinned npm integrity (sha512) below. Its
// CommonJS build is wrapped, file by file, into one classic script with a
// small require(); nothing in it is changed.
import { createHash } from 'node:crypto';
import { readFile, writeFile, mkdir, mkdtemp, rm, readdir } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join, dirname, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

export const VERSION = '6.2.5';
export const INTEGRITY = 'sha512-CGnyrvbhPlWYMngksqrSSUT1BAVP49dZocrHuK0SvtR0D5TMs5wP0o3j7jexDJW01KSadjBp1M/71o/KR3nD1w==';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, '..', 'src', 'vendor', 'fake-indexeddb');
const tgz = process.argv[2];
if (!tgz) throw new Error('usage: node tools/vendor_fake_indexeddb.mjs fake-indexeddb-6.2.5.tgz');

const bytes = await readFile(tgz);
const got = `sha512-${createHash('sha512').update(bytes).digest('base64')}`;
if (got !== INTEGRITY) throw new Error(`the tarball is not fake-indexeddb ${VERSION} (integrity ${got})`);

const tmp = await mkdtemp(join(tmpdir(), 'fidb-'));
try {
  execFileSync('tar', ['-xzf', tgz, '-C', tmp]);
  const pkg = join(tmp, 'package');
  const meta = JSON.parse(await readFile(join(pkg, 'package.json'), 'utf8'));
  if (meta.name !== 'fake-indexeddb' || meta.version !== VERSION) throw new Error('unexpected package.json');
  async function walk(d) {
    const out = [];
    for (const e of await readdir(d, { withFileTypes: true })) {
      const p = join(d, e.name);
      if (e.isDirectory()) out.push(...(await walk(p)));
      else if (e.name.endsWith('.js')) out.push(p);
    }
    return out;
  }
  const files = [...(await walk(join(pkg, 'build', 'cjs'))), join(pkg, 'auto', 'index.js')].sort();
  const mods = [];
  for (const f of files) {
    const rel = relative(pkg, f).split(sep).join('/');
    const src = await readFile(f, 'utf8');
    if (/\brequire\((?!["']\.{1,2}\/)/.test(src)) throw new Error(`${rel} requires a package outside fake-indexeddb`);
    mods.push(`${JSON.stringify(rel)}: function (module, exports, require) {\n${src}\n}`);
  }
  const bundle = `/* fake-indexeddb ${VERSION} (https://github.com/dumbmatter/fakeIndexedDB), Apache License 2.0, see LICENSE.
 * Generated by tools/vendor_fake_indexeddb.mjs from the npm tarball (${INTEGRITY}): its CommonJS
 * build and auto/index.js, unchanged, wrapped in one script. Loaded only inside dApp frames, where it
 * gives the dApp an in-memory IndexedDB (an opaque origin has none). */
(function () {
  'use strict';
  var defs = {
${mods.join(',\n')}
  };
  var cache = {};
  function resolve(from, spec) {
    var parts = from.split('/');
    parts.pop();
    spec.split('/').forEach(function (s) {
      if (s === '..') parts.pop();
      else if (s !== '.') parts.push(s);
    });
    return parts.join('/');
  }
  function load(path) {
    if (cache[path]) return cache[path].exports;
    var def = defs[path];
    if (!def) throw new Error('fake-indexeddb: missing module ' + path);
    var module = { exports: {} };
    cache[path] = module;
    def(module, module.exports, function (spec) { return load(resolve(path, spec)); });
    return module.exports;
  }
  load('auto/index.js');
})();
`;
  await mkdir(outDir, { recursive: true });
  await writeFile(join(outDir, 'fake-indexeddb.js'), bundle);
  await writeFile(join(outDir, 'LICENSE'), await readFile(join(pkg, 'LICENSE')));
  console.log(`wrote ${relative(process.cwd(), join(outDir, 'fake-indexeddb.js'))} (${bundle.length} bytes, ${mods.length} modules)`);
} finally {
  await rm(tmp, { recursive: true, force: true });
}
