// Generates test/beam/contracts/airdrop/fixtures/fee_vectors.json: the
// Airdrop creation fee for a set of totals, computed with the exact uint64_t
// statements of LightWallet contracts/airdrop/app.cpp (On_user_create_batch)
// and contract.cpp (Method_2), so the Dart port can be checked against the
// C++ arithmetic, wrap-around included.
//
//   clang++ -std=c++17 -O0 -o /tmp/fee_vectors fee_vectors.cpp
//   /tmp/fee_vectors > ../fixtures/fee_vectors.json

#include <cstdint>
#include <cstdio>
#include <vector>

typedef uint64_t Amount;
static const uint32_t FEE_BPS = 100;     // contract.h
static const uint32_t BPS_TOTAL = 10000; // contract.h

// Verbatim from app.cpp / contract.cpp.
static Amount CreationFee(Amount totalValue)
{
    Amount fee = (totalValue * FEE_BPS) / BPS_TOTAL;
    if (fee == 0 && totalValue > 0)
        fee = 1;
    return fee;
}

int main()
{
    const Amount max = UINT64_MAX;
    std::vector<Amount> totals = {
        0, 1, 2, 99, 100, 101, 199, 200, 201, 9999, 10000, 10001,
        19999, 20000, 100000, 200000,            // 2 x 0.001 BEAM
        1000000000, 1010000000,                  // 10 BEAM
        12345678901ull, 99999999999ull,
        max / 100 - 1, max / 100, max / 100 + 1, // the wrap boundary
        max / 50, max / 2, max - 1, max,
    };
    std::printf("{\n \"_comment\": \"Generated by tool/fee_vectors.cpp from the C++ "
                "fee statements of the Airdrop app shader and contract.\",\n");
    std::printf(" \"vectors\": [\n");
    for (size_t i = 0; i < totals.size(); i++)
        std::printf("  [\"%llu\", \"%llu\"]%s\n",
                    (unsigned long long) totals[i],
                    (unsigned long long) CreationFee(totals[i]),
                    i + 1 < totals.size() ? "," : "");
    std::printf(" ]\n}\n");
    return 0;
}
